version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html  #la ruta donde alojas tu frontend en EC2
    overwrite: true
hooks:
  BeforeInstall:
    - location: script/before_install.sh
      timeout: 180
      runas: root  # Ejecutar como root para evitar problemas de permisos
  AfterInstall:
    - location: script/after_install.sh
      timeout: 180
      runas: root  
  ApplicationStart:
    - location: script/start_server.sh
      timeout: 180
      runas: root  
